### ISSUE TITLE
project is stale / needs complete pass

### ISSUE THREAD

**Issue by opaugam** [autodesk-cloud/ochonetes#10]

**Comment by xiaods** [comment]
@opaugam what mean for stale? this project will cancel?

**Comment by opaugam** [comment]
sorry for being unclear - by stale I mean we haven't had time to focus on it. We moved really fast on the Mesos/Marathon implementation & will need to refresh the K8S one. Question of priorities & timing :)

We are not dropping this project and will be back on it when time allows.
